/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as MemoriesIndexRouteImport } from './routes/memories.index'
import { Route as MemoriesSlugRouteImport } from './routes/memories.$slug'
import { Route as ApiPublicMemoryMediaRouteImport } from './routes/api/public/memory-media'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const MemoriesIndexRoute = MemoriesIndexRouteImport.update({
  id: '/memories/',
  path: '/memories/',
  getParentRoute: () => rootRouteImport,
} as any)
const MemoriesSlugRoute = MemoriesSlugRouteImport.update({
  id: '/memories/$slug',
  path: '/memories/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMemoryMediaRoute = ApiPublicMemoryMediaRouteImport.update({
  id: '/api/public/memory-media',
  path: '/api/public/memory-media',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/memories/': typeof MemoriesIndexRoute
  '/api/public/memory-media': typeof ApiPublicMemoryMediaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/memories': typeof MemoriesIndexRoute
  '/api/public/memory-media': typeof ApiPublicMemoryMediaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/memories/$slug': typeof MemoriesSlugRoute
  '/memories/': typeof MemoriesIndexRoute
  '/api/public/memory-media': typeof ApiPublicMemoryMediaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/memories/$slug'
    | '/memories/'
    | '/api/public/memory-media'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/memories/$slug'
    | '/memories'
    | '/api/public/memory-media'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/.well-known/oauth-protected-resource'
    | '/memories/$slug'
    | '/memories/'
    | '/api/public/memory-media'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  MemoriesSlugRoute: typeof MemoriesSlugRoute
  MemoriesIndexRoute: typeof MemoriesIndexRoute
  ApiPublicMemoryMediaRoute: typeof ApiPublicMemoryMediaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/': {
      id: '/memories/'
      path: '/memories'
      fullPath: '/memories/'
      preLoaderRoute: typeof MemoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/memories/$slug': {
      id: '/memories/$slug'
      path: '/memories/$slug'
      fullPath: '/memories/$slug'
      preLoaderRoute: typeof MemoriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/memory-media': {
      id: '/api/public/memory-media'
      path: '/api/public/memory-media'
      fullPath: '/api/public/memory-media'
      preLoaderRoute: typeof ApiPublicMemoryMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  MemoriesSlugRoute: MemoriesSlugRoute,
  MemoriesIndexRoute: MemoriesIndexRoute,
  ApiPublicMemoryMediaRoute: ApiPublicMemoryMediaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
